"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing
import waCommon.WACommon_pb2
import waE2E.WAWebProtobufsE2E_pb2
import waWeb.WAWebProtobufsWeb_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GroupHistory(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: builtins.int
    UNCOUNTEDASSOCIATEDMESSAGELISTS_FIELD_NUMBER: builtins.int
    COMMENTMESSAGES_FIELD_NUMBER: builtins.int
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[waWeb.WAWebProtobufsWeb_pb2.WebMessageInfo]: ...
    @property
    def uncountedAssociatedMessageLists(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___UnCountedAssociatedMessageList]: ...
    @property
    def commentMessages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[waWeb.WAWebProtobufsWeb_pb2.WebMessageInfo]: ...
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[waWeb.WAWebProtobufsWeb_pb2.WebMessageInfo] | None = ...,
        uncountedAssociatedMessageLists: collections.abc.Iterable[Global___UnCountedAssociatedMessageList] | None = ...,
        commentMessages: collections.abc.Iterable[waWeb.WAWebProtobufsWeb_pb2.WebMessageInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["commentMessages", b"commentMessages", "messages", b"messages", "uncountedAssociatedMessageLists", b"uncountedAssociatedMessageLists"]) -> None: ...

Global___GroupHistory: typing_extensions.TypeAlias = GroupHistory

@typing.final
class UnCountedAssociatedMessageList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: builtins.int
    PARENTMESSAGE_FIELD_NUMBER: builtins.int
    ASSOCIATIONTYPE_FIELD_NUMBER: builtins.int
    associationType: waE2E.WAWebProtobufsE2E_pb2.MessageAssociation.AssociationType.ValueType
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[waWeb.WAWebProtobufsWeb_pb2.WebMessageInfo]: ...
    @property
    def parentMessage(self) -> waCommon.WACommon_pb2.MessageKey: ...
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[waWeb.WAWebProtobufsWeb_pb2.WebMessageInfo] | None = ...,
        parentMessage: waCommon.WACommon_pb2.MessageKey | None = ...,
        associationType: waE2E.WAWebProtobufsE2E_pb2.MessageAssociation.AssociationType.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["associationType", b"associationType", "parentMessage", b"parentMessage"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["associationType", b"associationType", "messages", b"messages", "parentMessage", b"parentMessage"]) -> None: ...

Global___UnCountedAssociatedMessageList: typing_extensions.TypeAlias = UnCountedAssociatedMessageList

@typing.final
class WebMessageInfoWithMessageBytes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    MESSAGEBYTES_FIELD_NUMBER: builtins.int
    messageBytes: builtins.bytes
    @property
    def key(self) -> waCommon.WACommon_pb2.MessageKey: ...
    def __init__(
        self,
        *,
        key: waCommon.WACommon_pb2.MessageKey | None = ...,
        messageBytes: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["key", b"key", "messageBytes", b"messageBytes"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "messageBytes", b"messageBytes"]) -> None: ...

Global___WebMessageInfoWithMessageBytes: typing_extensions.TypeAlias = WebMessageInfoWithMessageBytes

@typing.final
class UnCountedAssociatedMessageListWithMessageBytes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: builtins.int
    PARENTMESSAGE_FIELD_NUMBER: builtins.int
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___WebMessageInfoWithMessageBytes]: ...
    @property
    def parentMessage(self) -> waCommon.WACommon_pb2.MessageKey: ...
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[Global___WebMessageInfoWithMessageBytes] | None = ...,
        parentMessage: waCommon.WACommon_pb2.MessageKey | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["parentMessage", b"parentMessage"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["messages", b"messages", "parentMessage", b"parentMessage"]) -> None: ...

Global___UnCountedAssociatedMessageListWithMessageBytes: typing_extensions.TypeAlias = UnCountedAssociatedMessageListWithMessageBytes

@typing.final
class GroupHistoryWithMessageBytes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: builtins.int
    UNCOUNTEDASSOCIATEDMESSAGELISTS_FIELD_NUMBER: builtins.int
    COMMENTMESSAGES_FIELD_NUMBER: builtins.int
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___WebMessageInfoWithMessageBytes]: ...
    @property
    def uncountedAssociatedMessageLists(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___UnCountedAssociatedMessageListWithMessageBytes]: ...
    @property
    def commentMessages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___WebMessageInfoWithMessageBytes]: ...
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[Global___WebMessageInfoWithMessageBytes] | None = ...,
        uncountedAssociatedMessageLists: collections.abc.Iterable[Global___UnCountedAssociatedMessageListWithMessageBytes] | None = ...,
        commentMessages: collections.abc.Iterable[Global___WebMessageInfoWithMessageBytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["commentMessages", b"commentMessages", "messages", b"messages", "uncountedAssociatedMessageLists", b"uncountedAssociatedMessageLists"]) -> None: ...

Global___GroupHistoryWithMessageBytes: typing_extensions.TypeAlias = GroupHistoryWithMessageBytes
